version: '3'
services:
  http:
    build: ./docker
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    working_dir: /app
    environment:
        LANG: "C.UTF-8"
    command: uwsgi --ini /app/uwsgi.ini
