"""initial

Revision ID: 6df0d5aac594
Revises: 
Create Date: 2017-11-28 23:39:40.098546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df0d5aac594'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('notify_at', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timezones',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timezones')
    op.drop_table('reminders')
    # ### end Alembic commands ###
