"""uuid ids

Revision ID: b6a452c73bc3
Revises: 6df0d5aac594
Create Date: 2017-12-06 20:57:39.660665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a452c73bc3'
down_revision = '6df0d5aac594'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('reminders_copy',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.Text(), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('notify_at', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), server_default='pending', nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.execute('''\
        insert into reminders_copy (id, user_id, message, notify_at, status)
        select "some-id-" || id, user_id, message, notify_at, status from reminders
    ''')
    op.execute('drop table reminders')
    op.execute('alter table reminders_copy rename to reminders')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
